### ISSUE TITLE
Invite more collaborators who are already on GitHub #81

### ISSUE THREAD

**Issue by cesine** [LowResourceLanguages/about#3]
We'd like to welcome other githubers to join us on the [LowResourceLanguage](https://github.com/orgs/LowResourceLanguages/teams/contributors) project.

If anyone else wants to join, let us know about you and send us a link to your github so we can see what you specialize in.

We don't really have any ground rules about who can join, but the important thing is to be friendly and supportive and help out when you can. Most of us have jobs and/or careers and/or studies and/or kids, so we can't be 100% available but the little bit we can do, will benefit the greater good!

After you have been invited, if you want your membership to be public, you can publish by opening the   [team page](https://github.com/orgs/LowResourceLanguages/teams/contributors) like this:

<img width="1009" alt="screen shot 2015-08-02 at 10 42 14 am" src="https://cloud.githubusercontent.com/assets/196199/9026598/324acf68-3903-11e5-89e3-e470f913a5f7.png">

**Comment by cesine** [comment]
I invited a few who I know work on LRL, or who have already contributed to richard's list.

<img width="311" alt="screen shot 2015-08-02 at 11 19 00 am" src="https://cloud.githubusercontent.com/assets/196199/9026725/50b0aedc-3908-11e5-8bd4-a78054a93237.png">

**Comment by RichardLitt** [comment]
:+1: Thanks for doing this, @cesine!

**Comment by cesine** [comment]
Welcome @alvations @arne-cl @mapmeld @jrwdunham @gretchenmcc @xrotwang @kscanne @ctschroeder ! exiting to meet you all :) this issue has instructions on how to make yourselves public members if you want the icon to show on your github profile

**Comment by cesine** [comment]
I'm helping out on https://github.com/RichardLitt/endangered-languages/issues/91 and I found that cos is also on github 
- https://github.com/kscanne?tab=repositories
