### ISSUE TITLE
Create more visibility for projects who are popular

### ISSUE THREAD

**Issue by cesine** [LowResourceLanguages/about#4]
Some of the projects on the list like Aikuma need a lot of attention, they are in production, they are busy on github, their code and their development is 100% open and if someone is looking for an Android codebase to record stories, their codebase is perfect.

lets see if we can use something in the list that shows the number of stars and forks on a project.... I found this. I will see if it works in a .md 

```
<iframe src="https://ghbtns.com/github-btn.html?user=twbs&repo=bootstrap&type=star&count=true" frameborder="0" scrolling="0" width="170px" height="20px"></iframe>
```

**Comment by RichardLitt** [comment]
I think that this can be closed now?

**Comment by cesine** [comment]
I guess, we dont know if we succeeded yet in the visibility study https://github.com/LowResourceLanguages/about/tree/experiment/improving-visibility/visibility but we did start at least :)

**Comment by RichardLitt** [comment]
:)
