### ISSUE TITLE
Try rmd for auto updating visibility analysis

### ISSUE THREAD

**Issue by cesine** [LowResourceLanguages/about#7]
https://github.com/sahirbhatnagar/knitr-tutorial

**Comment by cesine** [comment]
Example with JavaScript integration http://sahirbhatnagar.com/heatmap/

**Comment by RichardLitt** [comment]
Huh, interesting. What are you envisioning here?

**Comment by cesine** [comment]
for now nothing too exciting, just an rmd script which will update the a data table and display stats and plots at each measure. if we find something interesting we can add javascript, if not then its just to automate the statistics with the data collection so that the readme shows the experiment as it goes. i didnt have time this weekend (scraping and painting wrought iron balconies)

**Comment by RichardLitt** [comment]
Cool Which statistics, though? I'm just not sure exactly why this is in the about repo.

**Comment by cesine** [comment]
sorry, its for this file: https://github.com/LowResourceLanguages/about/blob/experiment/improving-visibility/visibility/README.md the visibility experiment readme, not for the about readme. 

i guess we could move the experiment elsewhere? but I thought eventually it made sense to have an experiments directory in the about repo. since they should help in explaining what the org is about.

**Comment by RichardLitt** [comment]
Ah, cool! Yeah, that works well. I would just keep it in here, it's meta enough.
